import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts ./types`.

export type Posts = Models.Row & {
    creator: Users;
    caption: string | null;
    tags: string[] | null;
    imageUrl: string;
    imageId: string;
    location: string | null;
    save: Saves[];
    likesCount: number;
    savesCount: number;
    likes: Likes[];
}

export type Users = Models.Row & {
    posts: Posts[];
    name: string;
    username: string | null;
    email: string;
    bio: string | null;
    imageId: string | null;
    imageUrl: string;
    save: Saves[];
    liked: Likes[];
    followers: Follows[];
    followees: Follows[];
    followersCount: number;
    followeesCount: number;
    likeCount: number;
    saveCount: number;
    postCount: number;
}

export type Saves = Models.Row & {
    user: Users;
    post: Posts;
}

export type Likes = Models.Row & {
    post: Posts;
    user: Users;
}

export type Follows = Models.Row & {
    follower: Users;
    followee: Users;
}
